services:
  recommender:
    build:
      context: .
      dockerfile: TCPServer/Dockerfile
    container_name: recommendation_server
    volumes:
      - reccomendation_data_base:/usr/src/data
    networks:
      - app_network
    environment:
      PORT: ${RECOMMENDATION_PORT:-5555} 
    entrypoint: ["./netflix_server"]
    command: ["${RECOMMENDATION_PORT:-5555}"]

  app:
    build:
      context: .
      dockerfile: WebServer/Dockerfile
    container_name: app_server
    ports:
      - "${APP_PORT:-3000}:${CONTAINER_PORT:-3000}"
    networks:
      - app_network
    volumes:
      - profile_pictures:/usr/src/app/uploadsProfilePicture
      - availlible_movies:/usr/src/app/availableMovies
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      RECOMMENDATION_IP: recommendation_server  
      RECOMMENDATION_PORT: ${RECOMMENDATION_PORT:-5555}
      PORT: ${CONTAINER_PORT:-3000} 
      JWT_SECRET: ${JWT_SECRET}
    command: ["npm", "start"]

volumes:
  reccomendation_data_base:
  profile_pictures:
  availlible_movies:
networks:
  app_network:
    driver: bridge
